version: '3'
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    volumes:
      - data:/data/db
  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
    depends_on:
      - mongodb
volumes:
  data: